INSERT INTO siscof.governances(id ,name) VALUES(1,'Gobernación de Arica');
INSERT INTO siscof.governances(id ,name) VALUES(2,'Gobernación de Parinacota');
INSERT INTO siscof.governances(id ,name) VALUES(3,'Gobernación de Iquique');
INSERT INTO siscof.governances(id ,name) VALUES(4,'Gobernación de Tamarugal');
INSERT INTO siscof.governances(id ,name) VALUES(5,'Gobernación de Antofagasta');
INSERT INTO siscof.governances(id ,name) VALUES(6,'Gobernación de El loa');
INSERT INTO siscof.governances(id ,name) VALUES(7,'Gobernación de Tocopilla');
INSERT INTO siscof.governances(id ,name) VALUES(8,'Gobernación de Copiapo');
INSERT INTO siscof.governances(id ,name) VALUES(9,'Gobernación de Huasco');
INSERT INTO siscof.governances(id ,name) VALUES(10,'Gobernación de Chañaral');
INSERT INTO siscof.governances(id ,name) VALUES(11,'Gobernación de Elqui');
INSERT INTO siscof.governances(id ,name) VALUES(12,'Gobernación de Limari');
INSERT INTO siscof.governances(id ,name) VALUES(13,'Gobernación de Choapa');
INSERT INTO siscof.governances(id ,name) VALUES(14,'Gobernación de Valparaiso');
INSERT INTO siscof.governances(id ,name) VALUES(15,'Gobernación de Quillota');
INSERT INTO siscof.governances(id ,name) VALUES(16,'Gobernación de San Antonio');
INSERT INTO siscof.governances(id ,name) VALUES(17,'Gobernación de San Felipe de Aconcagua');
INSERT INTO siscof.governances(id ,name) VALUES(18,'Gobernación de Los Andes');
INSERT INTO siscof.governances(id ,name) VALUES(19,'Gobernación de Petorca');
INSERT INTO siscof.governances(id ,name) VALUES(20,'Gobernación de Isla de Pascua');
INSERT INTO siscof.governances(id ,name) VALUES(21,'Gobernación de Marga marga');
INSERT INTO siscof.governances(id ,name) VALUES(22,'Gobernación de Maipo');
INSERT INTO siscof.governances(id ,name) VALUES(23,'Gobernación de Cordillera');
INSERT INTO siscof.governances(id ,name) VALUES(24,'Gobernación de Talagante');
INSERT INTO siscof.governances(id ,name) VALUES(25,'Gobernación de Melipilla');
INSERT INTO siscof.governances(id ,name) VALUES(26,'Gobernación de Chacabuco');
INSERT INTO siscof.governances(id ,name) VALUES(27,'Gobernación de Santiago');
INSERT INTO siscof.governances(id ,name) VALUES(28,'Gobernación de Cachapoal');
INSERT INTO siscof.governances(id ,name) VALUES(29,'Gobernación de Colchagua');
INSERT INTO siscof.governances(id ,name) VALUES(30,'Gobernación de Cardenal Caro');
INSERT INTO siscof.governances(id ,name) VALUES(31,'Gobernación de Talca');
INSERT INTO siscof.governances(id ,name) VALUES(32,'Gobernación de Curico');
INSERT INTO siscof.governances(id ,name) VALUES(33,'Gobernación de Linares');
INSERT INTO siscof.governances(id ,name) VALUES(34,'Gobernación de Cauquenes');
INSERT INTO siscof.governances(id ,name) VALUES(35,'Gobernación de Itata');
INSERT INTO siscof.governances(id ,name) VALUES(36,'Gobernación de Diguillin');
INSERT INTO siscof.governances(id ,name) VALUES(37,'Gobernación de Punilla');
INSERT INTO siscof.governances(id ,name) VALUES(38,'Gobernación de Concepcion');
INSERT INTO siscof.governances(id ,name) VALUES(39,'Gobernación de Bio Bio');
INSERT INTO siscof.governances(id ,name) VALUES(40,'Gobernación de Arauco');
INSERT INTO siscof.governances(id ,name) VALUES(41,'Gobernación de Cautin');
INSERT INTO siscof.governances(id ,name) VALUES(42,'Gobernación de Malleco');
INSERT INTO siscof.governances(id ,name) VALUES(43,'Gobernación de Valdivia');
INSERT INTO siscof.governances(id ,name) VALUES(44,'Gobernación de Ranco');
INSERT INTO siscof.governances(id ,name) VALUES(45,'Gobernación de LLanquihue');
INSERT INTO siscof.governances(id ,name) VALUES(46,'Gobernación de Osorno');
INSERT INTO siscof.governances(id ,name) VALUES(47,'Gobernación de Chiloe');
INSERT INTO siscof.governances(id ,name) VALUES(48,'Gobernación de Coyhaique');
INSERT INTO siscof.governances(id ,name) VALUES(49,'Gobernación de Aysen');
INSERT INTO siscof.governances(id ,name) VALUES(50,'Gobernación de General Carrera');
INSERT INTO siscof.governances(id ,name) VALUES(51,'Gobernación de Capitan Prat');
INSERT INTO siscof.governances(id ,name) VALUES(52,'Gobernación de Magallanes');
INSERT INTO siscof.governances(id ,name) VALUES(53,'Gobernación de Ultima Esperanza');
INSERT INTO siscof.governances(id ,name) VALUES(54,'Gobernación de Tierra del Fuego');
INSERT INTO siscof.governances(id ,name) VALUES(55,'Gobernación de la Antartica Chilena');


